osx_image: xcode8.4
dist: trusty
sudo: required
language: node_js
node_js: '11'

addons:
  chrome: stable # Install chrome stable on operating systems

os:
  - linux
  - osx

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
